# Generated by Django 5.2.7 on 2025-10-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
                ('body', models.TextField()),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('Images', models.ImageField(upload_to='')),
            ],
        ),
    ]
