# Generated by Django 5.2.7 on 2025-10-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Images',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
